name: 🚀Предложение по улучшению📈
description: Отправьте отчёт с предложением об улучшениии программы
title: "[ENHANCEMENT]: "
labels: ["enhancement"]
assignees: ["GSEvgenievich"]
body:
  - type: markdown
    attributes:
      value: |
        😄Благодарим за помощь в улучшении программы!!!
  - type: checkboxes
    id: new-enhancement
    attributes:
      label: ❓️Существует ли уже такое же предложение по улучшению?❓️
      description: Пожалуйста, проверьте, есть ли уже предложение по улучшению, похожее на Ваше.
      options:
      - label: ✅Я проверил существующие предложения по улучшению
        required: true
  - type: textarea
    id: enhancement-description
    attributes:
      label: 📝Описание улучшения
      description: Расскажите, какое улучшение программы вы предлагаете и как его реализовать
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 📝Шаги для воспроизведения
      description: Шаги для воспроизведения улучшения программы.
      placeholder: Пожалуйста, укажите шаги в виде списка
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: 📝Фактический результат 
      description: Фактический результат работы программы.
      placeholder: Пожалуйста, укажите шаги в виде списка
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: 📝Ожидаемый результат
      description: Ожидаемый результат работы программы после улучшения.
      placeholder: Пожалуйста, укажите шаги в виде списка
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: 📝Серьезность
      description: Укажите тип испрпавления
      options:
       - Улучшение UI
       - Улучшение быстродействия
       - Изменение существующего функционала
       - Добавление нового функционала
       - Другое
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: 📁Пожалуйста, прикрепите файл
      description: Загрузите файл, перетащив его сюда после создания задачи или выберите его вручную.
    validations:
      required: false
